<?php

return [
  "personal_loan"=> [
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "IDFC FIRST Bank",
    "YES Bank",
    "SMFG India Credit",
    "InCred",
    "Hero FinCorp",
    "Poonawalla Fincorp",
    "Kotak Bank",
    "Bajaj Finserv",
    "Tata Capital",
    "Aditya Birla",
    "CITI Bank",
    "RBL Bank",
    "Clix Capital",
    "IDFC Bank",
    "LoanTap",
    "PaySense",
    "FT Cash",
    "Muthoot Finance",
    "IndiaBulls",
    "Deutsche Bank",
    "L&T",
    "Tata Capital",
    "Reliance",
    "Shriram Bank",
    "DCB Bank",
    "HDFC Sales",
    "IIFL",
    "Bank of Baroda",
    "Edelweiss",
    "Federal Bank",
    "Canara Bank",
    "Ujjivan Small Finance",
    "DHFL",
    "IndusInd Bank",
    "Union Bank of India",
    "State Bank of India",
    "IDBI",
    "Punjab National Bank",
    "Indian Bank",
    "Bank of India",
    "Bank of Maharashtra",
    "karnataka bank",
    "AU Small Finance",
    "Punjab & Sind Bank",
    "Karur Vysya Bank",
    "HSBC",
    "MoneyWide",
    "Privo",
    "Bhanix Finance",
    "Prefr",
    "Piramal Finance"
  ],
  "home_loan"=> [
    "IDFC FIRST Bank",
    "HDFC Bank",
    "Axis Bank",
    "Kotak Bank",
    "ICICI Bank",
    "YES Bank",
    "IndiaBulls",
    "Deutsche Bank",
    "L&T",
    "Tata Capital",
    "Bajaj Finserv",
    "Reliance",
    "Hero FinCorp",
    "PNB Housing Finance",
    "HDFC Home loan",
    "HDFC Sales",
    "Godrej",
    "DCB Bank",
    "IIFL",
    "CITI Bank",
    "Bank of Baroda",
    "Piramal Finance",
    "Vastu Housing Finance",
    "DHFL",
    "Federal Bank",
    "Clix Capital",
    "Ujjivan Small Finance",
    "Capri Global",
    "IDFC Bank",
    "Hero Housing Finance",
    "Aadhar housing Finance",
    "Canara Bank",
    "Home First Finance",
    "Edelweiss",
    "Aditya Birla",
    "Muthoot Finance",
    "RBL Bank",
    "Poonawalla Fincorp",
    "SMFG India Credit",
    "IndusInd Bank",
    "Union Bank of India",
    "State Bank of India",
    "IDBI",
    "Punjab National Bank",
    "Indian Bank",
    "Bank of India",
    "Bank of Maharashtra",
    "karnataka bank",
    "LIC",
    "Punjab & Sind Bank",
    "Cholamandalam",
    "HSBC",
    "Karur Vysya Bank"
  ],
  "loan_against_property"=> [
    "Axis Bank",
    "Kotak Bank",
    "IDFC FIRST Bank",
    "ICICI Bank",
    "HDFC Bank",
    "YES Bank",
    "IndiaBulls",
    "Deutsche Bank",
    "L&T",
    "Tata Capital",
    "Bajaj Finserv",
    "SMFG India Credit",
    "Tata Capital",
    "Emirates NBD",
    "Capri Global",
    "Piramal Finance",
    "Godrej",
    "PNB Housing Finance",
    "Edelweiss",
    "Reliance",
    "Home First Finance",
    "HDFC Home loan",
    "InCred",
    "RBL Bank",
    "Vastu Housing Finance",
    "DCB Bank",
    "Shriram Bank",
    "IIFL",
    "Ujjivan Small Finance",
    "Hero Housing Finance",
    "Clix Capital",
    "IDFC Bank",
    "Aditya Birla",
    "CITI Bank",
    "Bank of Baroda",
    "Muthoot Finance",
    "Poonawalla Fincorp",
    "Federal Bank",
    "Canara Bank",
    "DHFL",
    "Hero FinCorp",
    "HDFC Sales",
    "Aadhar housing Finance",
    "IndusInd Bank",
    "Union Bank of India",
    "Digikredit",
    "State Bank of India",
    "IDBI",
    "Punjab National Bank",
    "Cholamandalam",
    "HSBC",
    "Arka Fincap"
  ],
  "business_loan"=> [
    "Axis Bank",
    "Kotak Bank",
    "HDFC Bank",
    "YES Bank",
    "HSBC",
    "SMFG India Credit",
    "Deutsche Bank",
    "Bajaj Finserv",
    "Tata Capital",
    "Hero FinCorp",
    "Shriram Bank",
    "Aditya Birla",
    "IIFL",
    "Edelweiss",
    "DHFL",
    "Ujjivan Small Finance",
    "NeoGrowth",
    "Lending kart",
    "FT Cash",
    "LoanTap",
    "Indifi Technologies",
    "Digikredit",
    "INTELLEGROW",
    "IndiaBulls",
    "Poonawalla Fincorp",
    "IDFC FIRST Bank",
    "ICICI Bank",
    "RBL Bank",
    "L&T",
    "IDFC Bank",
    "Tata Capital",
    "DCB Bank",
    "CITI Bank",
    "HDFC Sales",
    "Bank of Baroda",
    "Muthoot Finance",
    "Federal Bank",
    "Canara Bank",
    "Clix Capital",
    "Capri Global",
    "Piramal Finance",
    "IndusInd Bank",
    "Union Bank of India",
    "State Bank of India",
    "IDBI",
    "Punjab National Bank",
    "Bank of India",
    "UGRO Capital",
    "Arka Fincap"
  ]
];
